=== jad19925/SimSYS_Marquette_SeniorDesign/GameAssetRepository/QuizQuestionRepository/Symbolic/Working/items.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema elementFormDefault="qualified"
	xmlns:xs="http://www.w3.org/2001/XMLSchema">
	<xs:element name="item_list">
		<xs:complexType>
			<xs:sequence>
				<xs:element name="item" minOccurs="1">

					<xs:complexType>
						<xs:sequence>
							<xs:element name="id" minOccurs="1" type="xs:integer" />
							<xs:element name="knowledge" minOccurs="1" type="xs:string" />
							<xs:element name="area" minOccurs="1" type="xs:string" />
							<xs:element name="topic_list" minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="1"
											name="topics" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="expression" type="xs:string"
								minOccurs="1" />
							<xs:element name="learning_taxonomy_list" minOccurs="1">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" minOccurs="1"
											name="learning_taxonomy" type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element name="image_list">
								<xs:complexType>
									<xs:sequence>
										<xs:element maxOccurs="unbounded" name="image"
											type="xs:string" />
									</xs:sequence>
								</xs:complexType>
							</xs:element>
							<xs:element minOccurs="1" name="question_list">
								<xs:complexType>
									<xs:sequence>
										<xs:element name="question" minOccurs="1">
											<xs:complexType>
												<xs:sequence>
													<xs:element name="question_id" minOccurs="1"
														type="xs:integer" />
													<xs:element name="topic_list" minOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element maxOccurs="unbounded" minOccurs="1"
																	name="topics" type="xs:string" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="depth" minOccurs="1" type="xs:string" />
													<xs:element name="stem_lead-in_questions"
														minOccurs="1" type="xs:string" />
													<xs:element name="option_list" minOccurs="1">
														<xs:complexType>
															<xs:sequence>
																<xs:element minOccurs="1" maxOccurs="unbounded"
																	name="incorrect_option" type="xs:string" />
																<xs:element maxOccurs="1"
																	name="partiallly_correct_option" type="xs:string" />
																<xs:element maxOccurs="1" name="correct"
																	type="xs:string" />
															</xs:sequence>
														</xs:complexType>
													</xs:element>
													<xs:element name="hint" minOccurs="1" type="xs:string" />
													<xs:element name="correct_feedback" minOccurs="1"
														type="xs:string" />
													<xs:element name="incorrect_feedback" minOccurs="1"
														type="xs:string" />
													<xs:element name="correct_follow_up_question_list"
														minOccurs="1" type="xs:integer" />
													<xs:element name="incorrect_follow_up_question_list"
														minOccurs="1" type="xs:integer" />
												</xs:sequence>
											</xs:complexType>
										</xs:element>
									</xs:sequence>
								</xs:complexType>
							</xs:element>
						</xs:sequence>
					</xs:complexType>
				</xs:element>
			</xs:sequence>
		</xs:complexType>
	</xs:element>

</xs:schema>

=== jad19925/SimSYS_Marquette_SeniorDesign/GameAssetRepository/QuizQuestionRepository/Symbolic/GenerateXML/items.xml
<?xml version="1.0" encoding="UTF-8"?>
<item_list xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xsi:noNamespaceSchemaLocation="items.xsd">
  <item>
    <id>0</id>
    <knowledge>knowledge</knowledge>
    <area>area</area>
    <topic_list>
      <topics>topics</topics>
    </topic_list>
    <expression>expression</expression>
    <learning_taxonomy_list>
      <learning_taxonomy>learning_taxonomy</learning_taxonomy>
    </learning_taxonomy_list>
    <image_list>
      <image>image</image>
    </image_list>
    <question_list>
      <question>
        <question_id>0</question_id>
        <topic_list>
          <topics>topics</topics>
        </topic_list>
        <depth>depth</depth>
        <stem_lead-in_questions>stem_lead-in_questions</stem_lead-in_questions>
        <option_list>
          <incorrect_option>incorrect_option</incorrect_option>
          <partiallly_correct_option>partiallly_correct_option</partiallly_correct_option>
          <correct>correct</correct>
        </option_list>
        <hint>hint</hint>
        <correct_feedback>correct_feedback</correct_feedback>
        <incorrect_feedback>incorrect_feedback</incorrect_feedback>
        <correct_follow_up_question_list>0</correct_follow_up_question_list>
        <incorrect_follow_up_question_list>0</incorrect_follow_up_question_list>
      </question>
    </question_list>
  </item>
</item_list>
